### ISSUE TITLE
Please Add https://gruene-porta-westfalica.de/

### ISSUE THREAD

**Issue by BorgmaSt** [netzbegruenung/green-directory#205]
Hi there, can you please add 
https://gruene-porta-westfalica.de/

to the Green-Spider App?

Thanks 

Stefan

**Comment by marians** [comment]
The site is in https://github.com/netzbegruenung/green-directory/blob/master/data/countries/de/nw/minden-luebbecke/data.yaml#L85-L93

However I see that it is not showing up i green spider.

**Comment by marians** [comment]
Site should show up in Green Spider soon.

**Comment by BorgmaSt** [comment]
Hi Marian,
cah you please change the URL into 

https://gruene-porta-westfalica.de

because we will reboot this site in January and remove the forwarding

Regards

Stefan

**Comment by marians** [comment]
I'd like to change it once https://gruene-porta-westfalica.de/ is the canonical domain. When that's the case, please ping me again in a new issue or in https://chatbegruenung.de/channel/green-spider . Thanks!
