### ISSUE TITLE
bitte: https://pullach-gruene.de hinzufügen

### ISSUE THREAD

**Issue by fmklug** [netzbegruenung/green-directory#211]

**Comment by fbthb** [comment]
Ist bereits hier (ohne https, nur http):
https://github.com/netzbegruenung/green-directory/blob/master/data/countries/de/by/muenchen-land/data.yaml
bzw. im Green Spider hier: 
https://green-spider.netzbegruenung.de/sites/http%3A%2F%2Fpullach-gruene.de%2F
