### ISSUE TITLE
Please add https://www.gruene-stuhr.de/

### ISSUE THREAD

**Issue by MWP-Stuhr** [netzbegruenung/green-directory#256]
Please add our homepage to green spider:

https://www.gruene-stuhr.de/

**Comment by fbthb** [comment]
see #258

**Comment by fbthb** [comment]
Die Webseite ist zur Liste hinzugefügt. Mit dem nächsten Durchlauf wird die Seite dann auch auf green-spider.netzbegruenung.de erfasst. Dies kann allerdings noch einige Tage dauern.

**Comment by MWP-Stuhr** [comment]
klasse, vielen Dank.

Am Sa., 6. Juni 2020 um 11:37 Uhr schrieb Florian <notifications@github.com
