### ISSUE TITLE
Grüne Rösrath has the Twitter account of Grüne Euskirchen

### ISSUE THREAD

**Issue by mehlukas** [netzbegruenung/green-directory#4]
see https://github.com/netzbegruenung/green-directory/blob/9345e0c4e8db656e0c7bddb2361acff01949c67f/data/countries/de/nrw/data.yaml#L56

Maybe we should add a check for duplicate entries?

**Comment by marians** [comment]
Fixed in #5.

I wouldn't want to write a duplicate checker for now. Feel free any time. :)
