### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by tjulises** [netzbegruenung/green-directory#80]
Hey, I'm graphic designer and my aim is supporting open source projects and make my portfolio better. So, I can contribute on your project with making logo design. I am waiting your feedback! Have a nice day! :)

Best Regards,
TJ Ulises
Visual Communication Designer

**Comment by marians** [comment]
Hi @tjulises! Thanks for your kind offer! Looking at the selection of other projects you offered this service to, I wonder, what were your criteria to offer your help to green-directory?
