### ISSUE TITLE
Extend schema to represent parlimanentary groups

### ISSUE THREAD

**Issue by marians** [netzbegruenung/green-directory#87]
We'd like to be able to represent [parliamentary groups](https://en.wikipedia.org/wiki/Parliamentary_group) (German: Fraktion) and their contact details, websites and social media accounts.

Examples:

- https://www.gruene-bundestag.de/ (Fraktion von Bündnis 90/Die Grünen im Deutschen Bundestag)
- https://gruene-kreistag-pm.de/home/ (Fraktion von Bündnis 90/Die Grünen im Kreistag Potsdam)

**Comment by fishat64** [comment]
See: 
https://github.com/fishat64/green-directory/tree/add-parlimanentary-groups
